services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reby
    ports:
      - '5432:5432'
    volumes:
      - reby_postgres_data:/var/lib/postgresql/data

volumes:
  reby_postgres_data:
